from typing import Any

from .chandle import CHandle

class AuthOptions(CHandle):
    def __init__(self, handle: Any, **kwargs) -> None: ...
    @classmethod
    def createWithUser(cls, user: AuthUser) -> "AuthOptions": ...
    @classmethod
    def createWithApp(cls, appName: str) -> "AuthOptions": ...
    @classmethod
    def createWithToken(cls, token: str) -> "AuthOptions": ...
    @classmethod
    def createWithUserAndApp(cls, user: AuthUser, appName: str) -> "AuthOptions": ...
    def destroy(self) -> None: ...

class AuthUser(CHandle):
    def __init__(self, handle: Any) -> None: ...
    @classmethod
    def createWithLogonName(cls) -> "AuthUser": ...
    @classmethod
    def createWithActiveDirectoryProperty(cls, propertyName: str) -> "AuthUser": ...
    @classmethod
    def createWithManualOptions(cls, userId: str, ipAddress: str) -> "AuthUser": ...
