from typing import Any

from .chandle import CHandle

class EventDispatcher(CHandle):
    def __init__(self, numDispatcherThreads: int = ...) -> None: ...
    def start(self) -> Any: ...
    def stop(self, async_: bool = ..., **kwargs) -> Any: ...
