from builtins import Exception as _StandardException
from typing import Optional

class Exception(_StandardException):
    def __init__(self, description: str, errorCode: int) -> None: ...

class DuplicateCorrelationIdException(Exception): ...
class InvalidStateException(Exception): ...
class InvalidArgumentException(Exception): ...
class InvalidConversionException(Exception): ...
class IndexOutOfRangeException(Exception): ...
class NotFoundException(Exception): ...
class FieldNotFoundException(Exception): ...
class UnsupportedOperationException(Exception): ...
class UnknownErrorException(Exception): ...

class _ExceptionUtil:
    @staticmethod
    def raiseException(errorCode: int, description: Optional[str] = ...) -> None: ...
    @staticmethod
    def raiseOnError(errorCode: int, description: Optional[str] = ...) -> None: ...
