from typing import Any, Callable

class _SwigNonDynamicMeta(type):
    __setattr__: Any

ELEMENTDEFINITION_UNBOUNDED: int
ELEMENT_INDEX_END: int
SERVICEREGISTRATIONOPTIONS_PRIORITY_MEDIUM: int
SERVICEREGISTRATIONOPTIONS_PRIORITY_HIGH: int
CORRELATION_TYPE_UNSET: int
CORRELATION_TYPE_INT: int
CORRELATION_TYPE_POINTER: int
CORRELATION_TYPE_AUTOGEN: int
CORRELATION_MAX_CLASS_ID: int
MANAGEDPTR_COPY: int
MANAGEDPTR_DESTROY: int
DATETIME_YEAR_PART: int
DATETIME_MONTH_PART: int
DATETIME_DAY_PART: int
DATETIME_OFFSET_PART: int
DATETIME_HOURS_PART: int
DATETIME_MINUTES_PART: int
DATETIME_SECONDS_PART: int
DATETIME_MILLISECONDS_PART: int
DATETIME_FRACSECONDS_PART: int
DATETIME_DATE_PART: int
DATETIME_TIME_PART: int
DATETIME_TIMEMILLI_PART: int
DATETIME_TIMEFRACSECONDS_PART: int
EVENTTYPE_ADMIN: int
EVENTTYPE_SESSION_STATUS: int
EVENTTYPE_SUBSCRIPTION_STATUS: int
EVENTTYPE_REQUEST_STATUS: int
EVENTTYPE_RESPONSE: int
EVENTTYPE_PARTIAL_RESPONSE: int
EVENTTYPE_SUBSCRIPTION_DATA: int
EVENTTYPE_SERVICE_STATUS: int
EVENTTYPE_TIMEOUT: int
EVENTTYPE_AUTHORIZATION_STATUS: int
EVENTTYPE_RESOLUTION_STATUS: int
EVENTTYPE_TOPIC_STATUS: int
EVENTTYPE_TOKEN_STATUS: int
EVENTTYPE_REQUEST: int
STATUS_ACTIVE: int
STATUS_DEPRECATED: int
STATUS_INACTIVE: int
STATUS_PENDING_DEPRECATION: int
SUBSCRIPTIONSTATUS_UNSUBSCRIBED: int
SUBSCRIPTIONSTATUS_SUBSCRIBING: int
SUBSCRIPTIONSTATUS_SUBSCRIBED: int
SUBSCRIPTIONSTATUS_CANCELLED: int
SUBSCRIPTIONSTATUS_PENDING_CANCELLATION: int
CLIENTMODE_AUTO: int
CLIENTMODE_DAPI: int
CLIENTMODE_SAPI: int
CLIENTMODE_COMPAT_33X: int
RESOLVEMODE_DONT_REGISTER_SERVICES: int
RESOLVEMODE_AUTO_REGISTER_SERVICES: int
SEATTYPE_INVALID_SEAT: int
SEATTYPE_BPS: int
SEATTYPE_NONBPS: int
SERVICEREGISTRATIONOPTIONS_PRIORITY_LOW: int
REGISTRATIONPARTS_DEFAULT: int
REGISTRATIONPARTS_PUBLISHING: int
REGISTRATIONPARTS_OPERATIONS: int
REGISTRATIONPARTS_SUBSCRIBER_RESOLUTION: int
REGISTRATIONPARTS_PUBLISHER_RESOLUTION: int
TOPICLIST_NOT_CREATED: int
TOPICLIST_CREATED: int
TOPICLIST_FAILURE: int
RESOLUTIONLIST_UNRESOLVED: int
RESOLUTIONLIST_RESOLVED: int
RESOLUTIONLIST_RESOLUTION_FAILURE_BAD_SERVICE: int
RESOLUTIONLIST_RESOLUTION_FAILURE_SERVICE_AUTHORIZATION_FAILED: int
RESOLUTIONLIST_RESOLUTION_FAILURE_BAD_TOPIC: int
RESOLUTIONLIST_RESOLUTION_FAILURE_TOPIC_AUTHORIZATION_FAILED: int
MESSAGE_FRAGMENT_NONE: int
MESSAGE_FRAGMENT_START: int
MESSAGE_FRAGMENT_INTERMEDIATE: int
MESSAGE_FRAGMENT_END: int
MESSAGE_RECAPTYPE_NONE: int
MESSAGE_RECAPTYPE_SOLICITED: int
MESSAGE_RECAPTYPE_UNSOLICITED: int
ZFPUTIL_REMOTE_8194: int
ZFPUTIL_REMOTE_8196: int
IDENTITYUTIL_USERTYPE_UNKNOWN: int
IDENTITYUTIL_USERTYPE_APP_PORTAL: int
IDENTITYUTIL_USERTYPE_SANDBOX_EXCEL: int
DATATYPE_BOOL: int
DATATYPE_CHAR: int
DATATYPE_BYTE: int
DATATYPE_INT32: int
DATATYPE_INT64: int
DATATYPE_FLOAT32: int
DATATYPE_FLOAT64: int
DATATYPE_STRING: int
DATATYPE_BYTEARRAY: int
DATATYPE_DATE: int
DATATYPE_TIME: int
DATATYPE_DECIMAL: int
DATATYPE_DATETIME: int
DATATYPE_ENUMERATION: int
DATATYPE_SEQUENCE: int
DATATYPE_CHOICE: int
DATATYPE_CORRELATION_ID: int
blpapi_Logging_SEVERITY_OFF: int
blpapi_Logging_SEVERITY_FATAL: int
blpapi_Logging_SEVERITY_ERROR: int
blpapi_Logging_SEVERITY_WARN: int
blpapi_Logging_SEVERITY_INFO: int
blpapi_Logging_SEVERITY_DEBUG: int
blpapi_Logging_SEVERITY_TRACE: int

def setLoggerCallbackWrapper(cb: Callable, severity: int): ...
def blpapi_HighPrecisionDatetime_fromTimePoint_wrapper(
    original: blpapi_TimePoint,
) -> blpapi_HighPrecisionDatetime_tag: ...
def blpapi_Logging_registerCallback(callback: Callable, thresholdSeverity: int): ...
def blpapi_Logging_logTestMessage(severity): ...
def blpapi_DiagnosticsUtil_memoryInfo_wrapper(): ...
def blpapi_EventDispatcher_stop(handle, asynch): ...
def blpapi_Service_printHelper(service, level, spacesPerLevel): ...
def blpapi_SchemaElementDefinition_printHelper(item, level, spacesPerLevel): ...
def blpapi_SchemaTypeDefinition_printHelper(item, level, spacesPerLevel): ...
def blpapi_Message_printHelper(message, level, spacesPerLevel): ...
def blpapi_SessionOptions_printHelper(sessionOptions, level, spacesPerLevel): ...
def blpapi_TestUtil_serializeServiceHelper(service): ...
def blpapi_SchemaTypeDefinition_hasElementDefinition(type, nameString, name): ...
def blpapi_ConstantList_hasConstant(list, nameString, name): ...
def blpapi_Service_hasEventDefinition(service, nameString, name): ...
def blpapi_Service_hasOperation(service, nameString, name): ...
def blpapi_SubscriptionList_addHelper(list, topic, correlationId, fields, options): ...
def blpapi_Name_hasName(nameString): ...
def blpapi_TopicList_createFromResolutionList(_from): ...

class intArray:
    thisown: Any
    def __init__(self, nelements) -> None: ...
    __swig_destroy__: Any
    def __getitem__(self, index): ...
    def __setitem__(self, index, value): ...
    def cast(self): ...
    @staticmethod
    def frompointer(t): ...

def intArray_frompointer(t): ...
def new_topicPtrArray(nelements): ...
def delete_topicPtrArray(ary): ...
def topicPtrArray_getitem(ary, index): ...
def topicPtrArray_setitem(ary, index, value): ...
def CorrelationId_t_equals(cid1, cid2): ...

class CorrelationId:
    thisown: Any
    value: Any
    UNSET_TYPE: Any
    INT_TYPE: Any
    OBJECT_TYPE: Any
    AUTOGEN_TYPE: Any
    MAX_CLASS_ID: Any
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def value(self): ...
    def __init__(self, *args) -> None: ...
    __swig_destroy__: Any
    def type(self): ...
    def classId(self): ...

class blpapi_CorrelationId_t__value:
    thisown: Any
    def __init__(self) -> None: ...
    __swig_destroy__: Any

def blpapi_Element_toPy(element): ...
def blpapi_Element_setElementFloat(element, nameString, name, value): ...
def blpapi_Element_setValueFloat(element, value, index): ...
def blpapi_Element_printHelper(element, level, spacesPerLevel): ...
def blpapi_Element_name(element): ...
def blpapi_Element_nameString(element): ...
def blpapi_Element_definition(element): ...
def blpapi_Element_datatype(element): ...
def blpapi_Element_isComplexType(element): ...
def blpapi_Element_isArray(element): ...
def blpapi_Element_isReadOnly(element): ...
def blpapi_Element_numValues(element): ...
def blpapi_Element_numElements(element): ...
def blpapi_Element_isNullValue(element, position): ...
def blpapi_Element_isNull(element): ...
def blpapi_Element_getElementAt(element, position): ...
def blpapi_Element_getElement(element, nameString, name): ...
def blpapi_Element_hasElementEx(
    element, nameString, name, excludeNullElements, reserved
): ...
def blpapi_Element_getValueAsBool(element, index): ...
def blpapi_Element_getValueAsChar(element, index): ...
def blpapi_Element_getValueAsInt32(element, index): ...
def blpapi_Element_getValueAsInt64(element, index): ...
def blpapi_Element_getValueAsFloat64(element, index): ...
def blpapi_Element_getValueAsString(element, index): ...
def blpapi_Element_getValueAsDatetime(element, index): ...
def blpapi_Element_getValueAsHighPrecisionDatetime(element, index): ...
def blpapi_Element_getValueAsElement(element, index): ...
def blpapi_Element_getValueAsName(element, index): ...
def blpapi_Element_getChoice(element): ...
def blpapi_Element_setValueBool(element, value, index): ...
def blpapi_Element_setValueInt32(element, value, index): ...
def blpapi_Element_setValueInt64(element, value, index): ...
def blpapi_Element_setValueString(element, value, index): ...
def blpapi_Element_setValueHighPrecisionDatetime(element, value, index): ...
def blpapi_Element_setValueFromName(element, value, index): ...
def blpapi_Element_setElementBool(element, nameString, name, value): ...
def blpapi_Element_setElementInt32(element, nameString, name, value): ...
def blpapi_Element_setElementInt64(element, nameString, name, value): ...
def blpapi_Element_setElementString(element, nameString, name, value): ...
def blpapi_Element_setElementHighPrecisionDatetime(
    element, nameString, name, value
): ...
def blpapi_Element_setElementFromName(element, elementName, name, buffer): ...
def blpapi_Element_appendElement(element): ...
def blpapi_Element_setChoice(element, nameCstr, name, index): ...
def blpapi_EventFormatter_setValueFloat(formatter, typeString, typeName, value): ...
def blpapi_EventFormatter_appendValueFloat(formatter, value): ...
def blpapi_EventFormatter_create(event): ...
def blpapi_EventFormatter_destroy(victim): ...
def blpapi_EventFormatter_appendMessage(formatter, typeString, typeName, topic): ...
def blpapi_EventFormatter_appendMessageSeq(
    formatter, typeString, typeName, topic, sequenceNumber, arg6
): ...
def blpapi_EventFormatter_appendResponse(formatter, typeString, typeName): ...
def blpapi_EventFormatter_appendRecapMessage(formatter, topic, cid): ...
def blpapi_EventFormatter_appendRecapMessageSeq(
    formatter, topic, cid, sequenceNumber, arg5
): ...
def blpapi_EventFormatter_appendFragmentedRecapMessage(
    formatter, typeString, typeName, topic, cid, fragmentType
): ...
def blpapi_EventFormatter_appendFragmentedRecapMessageSeq(
    formatter, typeString, typeName, topic, fragmentType, sequenceNumber
): ...
def blpapi_EventFormatter_setValueBool(formatter, typeString, typeName, value): ...
def blpapi_EventFormatter_setValueChar(formatter, typeString, typeName, value): ...
def blpapi_EventFormatter_setValueInt32(formatter, typeString, typeName, value): ...
def blpapi_EventFormatter_setValueInt64(formatter, typeString, typeName, value): ...
def blpapi_EventFormatter_setValueHighPrecisionDatetime(
    formatter, typeString, typeName, value
): ...
def blpapi_EventFormatter_setValueString(formatter, typeString, typeName, value): ...
def blpapi_EventFormatter_setValueFromName(formatter, typeString, typeName, value): ...
def blpapi_EventFormatter_setValueNull(formatter, typeString, typeName): ...
def blpapi_EventFormatter_pushElement(formatter, typeString, typeName): ...
def blpapi_EventFormatter_popElement(formatter): ...
def blpapi_EventFormatter_appendValueBool(formatter, value): ...
def blpapi_EventFormatter_appendValueChar(formatter, value): ...
def blpapi_EventFormatter_appendValueInt32(formatter, value): ...
def blpapi_EventFormatter_appendValueInt64(formatter, value): ...
def blpapi_EventFormatter_appendValueHighPrecisionDatetime(formatter, value): ...
def blpapi_EventFormatter_appendValueString(formatter, value): ...
def blpapi_EventFormatter_appendValueFromName(formatter, value): ...
def blpapi_EventFormatter_appendElement(formatter): ...
def Session_createHelper(parameters, eventHandlerFunc, dispatcher): ...
def Session_destroyHelper(sessionHandle, eventHandlerFunc): ...
def blpapi_EventDispatcher_create(numDispatcherThreads): ...
def blpapi_EventDispatcher_destroy(handle): ...
def blpapi_EventDispatcher_start(handle): ...
def ProviderSession_createHelper(parameters, eventHandlerFunc, dispatcher): ...
def ProviderSession_destroyHelper(sessionHandle, eventHandlerFunc): ...
def ProviderSession_terminateSubscriptionsOnTopic(sessionHandle, topic, message): ...
def blpapi_MessageFormatter_setValueFloat(formatter, typeName, value): ...
def blpapi_MessageFormatter_appendValueFloat(formatter, value): ...
def blpapi_MessageFormatter_setValueBool(formatter, typeName, value): ...
def blpapi_MessageFormatter_setValueChar(formatter, typeName, value): ...
def blpapi_MessageFormatter_setValueInt32(formatter, typeName, value): ...
def blpapi_MessageFormatter_setValueInt64(formatter, typeName, value): ...
def blpapi_MessageFormatter_setValueFloat32(formatter, typeName, value): ...
def blpapi_MessageFormatter_setValueFloat64(formatter, typeName, value): ...
def blpapi_MessageFormatter_setValueDatetime(formatter, typeName, value): ...
def blpapi_MessageFormatter_setValueHighPrecisionDatetime(
    formatter, typeName, value
): ...
def blpapi_MessageFormatter_setValueString(formatter, typeName, value): ...
def blpapi_MessageFormatter_setValueFromName(formatter, typeName, value): ...
def blpapi_MessageFormatter_setValueNull(formatter, typeName): ...
def blpapi_MessageFormatter_pushElement(formatter, typeName): ...
def blpapi_MessageFormatter_popElement(formatter): ...
def blpapi_MessageFormatter_appendValueBool(formatter, value): ...
def blpapi_MessageFormatter_appendValueChar(formatter, value): ...
def blpapi_MessageFormatter_appendValueInt32(formatter, value): ...
def blpapi_MessageFormatter_appendValueInt64(formatter, value): ...
def blpapi_MessageFormatter_appendValueFloat32(formatter, value): ...
def blpapi_MessageFormatter_appendValueFloat64(formatter, value): ...
def blpapi_MessageFormatter_appendValueDatetime(formatter, value): ...
def blpapi_MessageFormatter_appendValueHighPrecisionDatetime(formatter, value): ...
def blpapi_MessageFormatter_appendValueString(formatter, value): ...
def blpapi_MessageFormatter_appendValueFromName(formatter, value): ...
def blpapi_MessageFormatter_appendElement(formatter): ...
def blpapi_MessageFormatter_FormatMessageJson(formatter, message): ...
def blpapi_MessageFormatter_FormatMessageXml(formatter, message): ...
def blpapi_MessageFormatter_copy(original): ...
def blpapi_MessageFormatter_assign(rhs): ...
def blpapi_MessageFormatter_destroy(formatter): ...
def blpapi_AuthOptions_create_default(): ...
def blpapi_AuthOptions_create_forUserMode(user): ...
def blpapi_AuthOptions_create_forAppMode(app): ...
def blpapi_AuthOptions_create_forUserAndAppMode(user, app): ...
def blpapi_AuthOptions_create_forToken(token): ...
def blpapi_AuthOptions_duplicate(dup): ...
def blpapi_AuthOptions_copy(lhs, rhs): ...
def blpapi_AuthOptions_destroy(options): ...
def blpapi_AuthUser_createWithLogonName(): ...
def blpapi_AuthUser_createWithActiveDirectoryProperty(propertyName): ...
def blpapi_AuthUser_createWithManualOptions(userId, ipAddress): ...
def blpapi_AuthUser_duplicate(dup): ...
def blpapi_AuthUser_copy(lhs, rhs): ...
def blpapi_AuthUser_destroy(user): ...
def blpapi_AuthApplication_create(appName): ...
def blpapi_AuthApplication_duplicate(dup): ...
def blpapi_AuthApplication_copy(lhs, rhs): ...
def blpapi_AuthApplication_destroy(app): ...
def blpapi_AuthToken_create(tokenStr): ...
def blpapi_AuthToken_duplicate(dup): ...
def blpapi_AuthToken_copy(lhs, rhs): ...
def blpapi_AuthToken_destroy(token): ...

UNKNOWN_CLASS: int
INVALIDSTATE_CLASS: int
INVALIDARG_CLASS: int
IOERROR_CLASS: int
CNVERROR_CLASS: int
BOUNDSERROR_CLASS: int
NOTFOUND_CLASS: int
FLDNOTFOUND_CLASS: int
UNSUPPORTED_CLASS: int
ERROR_UNKNOWN: int
ERROR_ILLEGAL_ARG: int
ERROR_ILLEGAL_ACCESS: int
ERROR_INVALID_SESSION: int
ERROR_DUPLICATE_CORRELATIONID: int
ERROR_INTERNAL_ERROR: int
ERROR_RESOLVE_FAILED: int
ERROR_CONNECT_FAILED: int
ERROR_ILLEGAL_STATE: int
ERROR_CODEC_FAILURE: int
ERROR_INDEX_OUT_OF_RANGE: int
ERROR_INVALID_CONVERSION: int
ERROR_ITEM_NOT_FOUND: int
ERROR_IO_ERROR: int
ERROR_CORRELATION_NOT_FOUND: int
ERROR_SERVICE_NOT_FOUND: int
ERROR_LOGON_LOOKUP_FAILED: int
ERROR_DS_LOOKUP_FAILED: int
ERROR_UNSUPPORTED_OPERATION: int
ERROR_DS_PROPERTY_NOT_FOUND: int
ERROR_MSG_TOO_LARGE: int

def blpapi_getLastErrorDescription(resultCode): ...
def blpapi_SessionOptions_create(): ...
def blpapi_SessionOptions_destroy(parameters): ...
def blpapi_SessionOptions_setServerHost(parameters, serverHost): ...
def blpapi_SessionOptions_setServerPort(parameters, serverPort): ...
def blpapi_SessionOptions_setServerAddress(
    parameters, serverHost, serverPort, index
): ...
def blpapi_SessionOptions_removeServerAddress(parameters, index): ...
def blpapi_SessionOptions_setConnectTimeout(parameters, timeoutInMilliseconds): ...
def blpapi_SessionOptions_setDefaultServices(parameters, defaultServices): ...
def blpapi_SessionOptions_setDefaultSubscriptionService(
    parameters, serviceIdentifier
): ...
def blpapi_SessionOptions_setDefaultTopicPrefix(parameters, prefix): ...
def blpapi_SessionOptions_setAllowMultipleCorrelatorsPerMsg(
    parameters, allowMultipleCorrelatorsPerMsg
): ...
def blpapi_SessionOptions_setClientMode(parameters, clientMode): ...
def blpapi_SessionOptions_setMaxPendingRequests(parameters, maxPendingRequests): ...
def blpapi_SessionOptions_setAutoRestartOnDisconnection(parameters, autoRestart): ...
def blpapi_SessionOptions_setSessionIdentityOptions(parameters, authOptions, cid): ...
def blpapi_SessionOptions_setAuthenticationOptions(parameters, authOptions): ...
def blpapi_SessionOptions_setNumStartAttempts(parameters, numStartAttempts): ...
def blpapi_SessionOptions_setMaxEventQueueSize(parameters, maxEventQueueSize): ...
def blpapi_SessionOptions_setSlowConsumerWarningHiWaterMark(
    parameters, hiWaterMark
): ...
def blpapi_SessionOptions_setSlowConsumerWarningLoWaterMark(
    parameters, loWaterMark
): ...
def blpapi_SessionOptions_setDefaultKeepAliveInactivityTime(
    parameters, inactivityMsecs
): ...
def blpapi_SessionOptions_setDefaultKeepAliveResponseTimeout(
    parameters, timeoutMsecs
): ...
def blpapi_SessionOptions_setKeepAliveEnabled(parameters, isEnabled): ...
def blpapi_SessionOptions_setRecordSubscriptionDataReceiveTimes(
    parameters, shouldRecord
): ...
def blpapi_SessionOptions_setServiceCheckTimeout(paramaters, timeoutMsecs): ...
def blpapi_SessionOptions_setServiceDownloadTimeout(paramaters, timeoutMsecs): ...
def blpapi_SessionOptions_setTlsOptions(paramaters, tlsOptions): ...
def blpapi_SessionOptions_setFlushPublishedEventsTimeout(paramaters, timeoutMsecs): ...
def blpapi_SessionOptions_setBandwidthSaveModeDisabled(
    parameters, disableBandwidthSaveMode
): ...
def blpapi_SessionOptions_serverHost(parameters): ...
def blpapi_SessionOptions_serverPort(parameters): ...
def blpapi_SessionOptions_numServerAddresses(parameters): ...
def blpapi_SessionOptions_getServerAddress(parameters, index): ...
def blpapi_SessionOptions_connectTimeout(parameters): ...
def blpapi_SessionOptions_defaultServices(parameters): ...
def blpapi_SessionOptions_defaultSubscriptionService(parameters): ...
def blpapi_SessionOptions_defaultTopicPrefix(parameters): ...
def blpapi_SessionOptions_allowMultipleCorrelatorsPerMsg(parameters): ...
def blpapi_SessionOptions_clientMode(parameters): ...
def blpapi_SessionOptions_maxPendingRequests(parameters): ...
def blpapi_SessionOptions_autoRestartOnDisconnection(parameters): ...
def blpapi_SessionOptions_authenticationOptions(parameters): ...
def blpapi_SessionOptions_numStartAttempts(parameters): ...
def blpapi_SessionOptions_maxEventQueueSize(parameters): ...
def blpapi_SessionOptions_slowConsumerWarningHiWaterMark(parameters): ...
def blpapi_SessionOptions_slowConsumerWarningLoWaterMark(parameters): ...
def blpapi_SessionOptions_defaultKeepAliveInactivityTime(parameters): ...
def blpapi_SessionOptions_defaultKeepAliveResponseTimeout(parameters): ...
def blpapi_SessionOptions_keepAliveEnabled(parameters): ...
def blpapi_SessionOptions_recordSubscriptionDataReceiveTimes(parameters): ...
def blpapi_SessionOptions_serviceCheckTimeout(parameters): ...
def blpapi_SessionOptions_serviceDownloadTimeout(parameters): ...
def blpapi_SessionOptions_flushPublishedEventsTimeout(parameters): ...
def blpapi_SessionOptions_bandwidthSaveModeDisabled(parameters): ...
def blpapi_TlsOptions_destroy(parameters): ...
def blpapi_TlsOptions_createFromFiles(
    clientCredentialsFileName, clientCredentialsPassword, trustedCertificatesFileName
): ...
def blpapi_TlsOptions_createFromBlobs(
    clientCredentialsRawData, clientCredentialsPassword, trustedCertificatesRawData
): ...
def blpapi_TlsOptions_setTlsHandshakeTimeoutMs(paramaters, tlsHandshakeTimeoutMs): ...
def blpapi_TlsOptions_setCrlFetchTimeoutMs(paramaters, crlFetchTimeoutMs): ...
def blpapi_Name_create(nameString): ...
def blpapi_Name_destroy(name): ...
def blpapi_Name_equalsStr(name, string): ...
def blpapi_Name_string(name): ...
def blpapi_Name_length(name): ...
def blpapi_Name_findName(nameString): ...
def blpapi_SubscriptionList_create(): ...
def blpapi_SubscriptionList_destroy(list): ...
def blpapi_SubscriptionList_addResolved(list, subscriptionString, correlationId): ...
def blpapi_SubscriptionList_clear(list): ...
def blpapi_SubscriptionList_append(dest, src): ...
def blpapi_SubscriptionList_size(list): ...
def blpapi_SubscriptionList_correlationIdAt(list, index): ...
def blpapi_SubscriptionList_topicStringAt(list, index): ...
def blpapi_SubscriptionList_isResolvedAt(list, index): ...

class blpapi_TimePoint:
    thisown: Any
    d_value: Any
    def __init__(self) -> None: ...
    __swig_destroy__: Any

def blpapi_TimePointUtil_nanosecondsBetween(start, end): ...

class blpapi_Datetime_tag:
    thisown: Any
    parts: Any
    hours: Any
    minutes: Any
    seconds: Any
    milliSeconds: Any
    month: Any
    day: Any
    year: Any
    offset: Any
    def __init__(self) -> None: ...
    __swig_destroy__: Any

class blpapi_HighPrecisionDatetime_tag:
    thisown: Any
    datetime: Any
    picoseconds: Any
    def __init__(self) -> None: ...
    __swig_destroy__: Any

def blpapi_HighPrecisionDatetime_compare(lhs, rhs): ...
def blpapi_HighPrecisionDatetime_print(
    datetime, streamWriter, stream, level, spacesPerLevel
): ...
def blpapi_HighPrecisionDatetime_fromTimePoint(datetime, offset): ...
def blpapi_Constant_name(constant): ...
def blpapi_Constant_description(constant): ...
def blpapi_Constant_status(constant): ...
def blpapi_Constant_datatype(constant): ...
def blpapi_Constant_getValueAsChar(constant): ...
def blpapi_Constant_getValueAsInt32(constant): ...
def blpapi_Constant_getValueAsInt64(constant): ...
def blpapi_Constant_getValueAsFloat32(constant): ...
def blpapi_Constant_getValueAsFloat64(constant): ...
def blpapi_Constant_getValueAsDatetime(constant): ...
def blpapi_Constant_getValueAsString(constant): ...
def blpapi_ConstantList_name(list): ...
def blpapi_ConstantList_description(list): ...
def blpapi_ConstantList_numConstants(list): ...
def blpapi_ConstantList_datatype(constant): ...
def blpapi_ConstantList_status(list): ...
def blpapi_ConstantList_getConstant(constant, nameString, name): ...
def blpapi_ConstantList_getConstantAt(constant, index): ...
def blpapi_SchemaElementDefinition_name(field): ...
def blpapi_SchemaElementDefinition_description(field): ...
def blpapi_SchemaElementDefinition_status(field): ...
def blpapi_SchemaElementDefinition_type(field): ...
def blpapi_SchemaElementDefinition_numAlternateNames(field): ...
def blpapi_SchemaElementDefinition_getAlternateName(field, index): ...
def blpapi_SchemaElementDefinition_minValues(field): ...
def blpapi_SchemaElementDefinition_maxValues(field): ...
def blpapi_SchemaTypeDefinition_name(type): ...
def blpapi_SchemaTypeDefinition_description(type): ...
def blpapi_SchemaTypeDefinition_status(type): ...
def blpapi_SchemaTypeDefinition_datatype(type): ...
def blpapi_SchemaTypeDefinition_isComplexType(type): ...
def blpapi_SchemaTypeDefinition_isSimpleType(type): ...
def blpapi_SchemaTypeDefinition_isEnumerationType(type): ...
def blpapi_SchemaTypeDefinition_numElementDefinitions(type): ...
def blpapi_SchemaTypeDefinition_getElementDefinition(type, nameString, name): ...
def blpapi_SchemaTypeDefinition_getElementDefinitionAt(type, index): ...
def blpapi_SchemaTypeDefinition_enumeration(element): ...
def blpapi_Request_destroy(request): ...
def blpapi_Request_elements(request): ...
def blpapi_Request_setPreferredRoute(request, correlationId): ...
def blpapi_Request_getRequestId(request): ...
def blpapi_RequestTemplate_release(requestTemplate): ...
def blpapi_Operation_name(operation): ...
def blpapi_Operation_description(operation): ...
def blpapi_Operation_requestDefinition(operation): ...
def blpapi_Operation_numResponseDefinitions(operation): ...
def blpapi_Operation_responseDefinition(operation, index): ...
def blpapi_Operation_responseDefinitionFromName(operation, name): ...
def blpapi_Service_name(service): ...
def blpapi_Service_description(service): ...
def blpapi_Service_numOperations(service): ...
def blpapi_Service_numEventDefinitions(service): ...
def blpapi_Service_addRef(service): ...
def blpapi_Service_release(service): ...
def blpapi_Service_authorizationServiceName(service): ...
def blpapi_Service_getOperation(service, nameString, name): ...
def blpapi_Service_getOperationAt(service, index): ...
def blpapi_Service_getEventDefinition(service, nameString, name): ...
def blpapi_Service_getEventDefinitionAt(service, index): ...
def blpapi_Service_createRequest(service, operation): ...
def blpapi_Service_createAuthorizationRequest(service, operation): ...
def blpapi_Service_createPublishEvent(service): ...
def blpapi_Service_createAdminEvent(service): ...
def blpapi_Service_createResponseEvent(service, correlationId): ...
def blpapi_Message_messageType(message): ...
def blpapi_Message_topicName(message): ...
def blpapi_Message_service(message): ...
def blpapi_Message_numCorrelationIds(message): ...
def blpapi_Message_correlationId(message, index): ...
def blpapi_Message_getRequestId(message): ...
def blpapi_Message_elements(message): ...
def blpapi_Message_fragmentType(message): ...
def blpapi_Message_recapType(message): ...
def blpapi_Message_addRef(message): ...
def blpapi_Message_release(message): ...
def blpapi_Message_timeReceived(message): ...
def blpapi_Event_eventType(event): ...
def blpapi_Event_release(event): ...
def blpapi_EventQueue_create(): ...
def blpapi_EventQueue_destroy(eventQueue): ...
def blpapi_EventQueue_nextEvent(eventQueue, timeout): ...
def blpapi_EventQueue_purge(eventQueue): ...
def blpapi_EventQueue_tryNextEvent(eventQueue): ...
def blpapi_MessageIterator_create(event): ...
def blpapi_MessageIterator_destroy(iterator): ...
def blpapi_MessageIterator_next(iterator): ...
def blpapi_Identity_release(handle): ...
def blpapi_Identity_addRef(handle): ...
def blpapi_Identity_hasEntitlements(
    handle,
    service,
    eidElement,
    entitlementIds,
    numEntitlements,
    failedEntitlements,
    failedEntitlementsCount,
): ...
def blpapi_Identity_isAuthorized(handle, service): ...
def blpapi_Identity_getSeatType(handle): ...
def blpapi_HighResolutionClock_now(): ...
def blpapi_AbstractSession_cancel(session, correlationIds, requestLabel): ...
def blpapi_AbstractSession_sendAuthorizationRequest(
    session, request, identity, correlationId, eventQueue, requestLabel
): ...
def blpapi_AbstractSession_openService(session, serviceIdentifier): ...
def blpapi_AbstractSession_openServiceAsync(
    session, serviceIdentifier, correlationId
): ...
def blpapi_AbstractSession_generateToken(session, correlationId, eventQueue): ...
def blpapi_AbstractSession_generateManualToken(
    session, correlationId, user, manualIp, eventQueue
): ...
def blpapi_AbstractSession_getService(session, serviceIdentifier): ...
def blpapi_AbstractSession_createIdentity(session): ...
def blpapi_AbstractSession_generateAuthorizedIdentityAsync(
    session, authOptions, cid
): ...
def blpapi_AbstractSession_getAuthorizedIdentity(session, cid): ...
def blpapi_Session_start(session): ...
def blpapi_Session_startAsync(session): ...
def blpapi_Session_stop(session): ...
def blpapi_Session_stopAsync(session): ...
def blpapi_Session_nextEvent(session, timeoutInMilliseconds): ...
def blpapi_Session_tryNextEvent(session): ...
def blpapi_Session_subscribe(session, subscriptionList, handle, requestLabel): ...
def blpapi_Session_resubscribe(session, resubscriptionList, requestLabel): ...
def blpapi_Session_resubscribeWithId(
    session, resubscriptionList, resubscriptionId, requestLabel
): ...
def blpapi_Session_unsubscribe(session, unsubscriptionList, requestLabel): ...
def blpapi_Session_setStatusCorrelationId(
    session, service, identity, correlationId
): ...
def blpapi_Session_sendRequest(
    session, request, correlationId, identity, eventQueue, requestLabel
): ...
def blpapi_Session_sendRequestTemplate(session, requestTemplate, correlationId): ...
def blpapi_Session_createSnapshotRequestTemplate(
    session, subscriptionString, identity, correlationId
): ...
def blpapi_Session_getAbstractSession(session): ...
def blpapi_ResolutionList_extractAttributeFromResolutionSuccess(message, attribute): ...
def blpapi_ResolutionList_create(_from): ...
def blpapi_ResolutionList_destroy(list): ...
def blpapi_ResolutionList_add(list, topic, correlationId): ...
def blpapi_ResolutionList_addFromMessage(list, topic, correlationId): ...
def blpapi_ResolutionList_addAttribute(list, name): ...
def blpapi_ResolutionList_correlationIdAt(list, index): ...
def blpapi_ResolutionList_topicString(list, id): ...
def blpapi_ResolutionList_topicStringAt(list, index): ...
def blpapi_ResolutionList_status(list, id): ...
def blpapi_ResolutionList_statusAt(list, index): ...
def blpapi_ResolutionList_attribute(list, attribute, id): ...
def blpapi_ResolutionList_attributeAt(list, attribute, index): ...
def blpapi_ResolutionList_message(list, id): ...
def blpapi_ResolutionList_messageAt(list, index): ...
def blpapi_ResolutionList_size(list): ...
def blpapi_TestUtil_createEvent(eventType): ...
def blpapi_TestUtil_deserializeService(schema, schemaLength): ...
def blpapi_TestUtil_serializeService(streamWriter, stream, service): ...
def blpapi_TestUtil_appendMessage(event, messageType, properties): ...
def blpapi_TestUtil_createTopic(service, isActive): ...
def blpapi_TestUtil_getAdminMessageDefinition(messageName): ...
def blpapi_MessageProperties_create(): ...
def blpapi_MessageProperties_destroy(messageProperties): ...
def blpapi_MessageProperties_copy(src): ...
def blpapi_MessageProperties_assign(lhs, rhs): ...
def blpapi_MessageProperties_setCorrelationIds(messageProperties, correlationIds): ...
def blpapi_MessageProperties_setRecapType(messageProperties, recap, fragment): ...
def blpapi_MessageProperties_setTimeReceived(messageProperties, timestamp): ...
def blpapi_MessageProperties_setService(messageProperties, service): ...
def blpapi_MessageProperties_setRequestId(messageProperties, requestId): ...
def blpapi_Topic_create(_from): ...
def blpapi_Topic_destroy(victim): ...
def blpapi_Topic_compare(lhs, rhs): ...
def blpapi_Topic_service(topic): ...
def blpapi_Topic_isActive(topic): ...
def blpapi_TopicList_create(_from): ...
def blpapi_TopicList_destroy(list): ...
def blpapi_TopicList_add(list, topic, correlationId): ...
def blpapi_TopicList_addFromMessage(list, topic, correlationId): ...
def blpapi_TopicList_correlationIdAt(list, index): ...
def blpapi_TopicList_topicString(list, id): ...
def blpapi_TopicList_topicStringAt(list, index): ...
def blpapi_TopicList_status(list, id): ...
def blpapi_TopicList_statusAt(list, index): ...
def blpapi_TopicList_message(list, id): ...
def blpapi_TopicList_messageAt(list, index): ...
def blpapi_TopicList_size(list): ...
def blpapi_ProviderSession_create(parameters, handler, dispatcher, userData): ...
def blpapi_ProviderSession_destroy(session): ...
def blpapi_ProviderSession_start(session): ...
def blpapi_ProviderSession_startAsync(session): ...
def blpapi_ProviderSession_stop(session): ...
def blpapi_ProviderSession_stopAsync(session): ...
def blpapi_ProviderSession_nextEvent(session, timeoutInMilliseconds): ...
def blpapi_ProviderSession_tryNextEvent(session): ...
def blpapi_ProviderSession_registerService(
    session, serviceName, identity, registrationOptions
): ...
def blpapi_ProviderSession_activateSubServiceCodeRange(
    session, serviceName, begin, end, priority
): ...
def blpapi_ProviderSession_deactivateSubServiceCodeRange(
    session, serviceName, begin, end
): ...
def blpapi_ProviderSession_registerServiceAsync(
    session, serviceName, identity, correlationId, registrationOptions
): ...
def blpapi_ProviderSession_deregisterService(session, serviceName): ...
def blpapi_ProviderSession_resolve(session, resolutionList, resolveMode, identity): ...
def blpapi_ProviderSession_resolveAsync(
    session, resolutionList, resolveMode, identity
): ...
def blpapi_ProviderSession_createTopics(session, topicList, resolveMode, identity): ...
def blpapi_ProviderSession_createTopicsAsync(
    session, topicList, resolveMode, identity
): ...
def blpapi_ProviderSession_getTopic(session, message): ...
def blpapi_ProviderSession_createTopic(session, message): ...
def blpapi_ProviderSession_createServiceStatusTopic(session, service): ...
def blpapi_ProviderSession_deleteTopics(session, topics, numTopics): ...
def blpapi_ProviderSession_terminateSubscriptionsOnTopics(
    session, topics, numTopics, message
): ...
def blpapi_ProviderSession_publish(session, event): ...
def blpapi_ProviderSession_sendResponse(session, event, isPartialResponse): ...
def blpapi_ProviderSession_getAbstractSession(session): ...
def blpapi_ProviderSession_flushPublishedEvents(session, timeoutMsecs): ...
def blpapi_ServiceRegistrationOptions_create(): ...
def blpapi_ServiceRegistrationOptions_duplicate(parameters): ...
def blpapi_ServiceRegistrationOptions_destroy(parameters): ...
def blpapi_ServiceRegistrationOptions_copy(lhs, rhs): ...
def blpapi_ServiceRegistrationOptions_addActiveSubServiceCodeRange(
    parameters, start, end, priority
): ...
def blpapi_ServiceRegistrationOptions_removeAllActiveSubServiceCodeRanges(
    parameters,
): ...
def blpapi_ServiceRegistrationOptions_setGroupId(parameters, groupId): ...
def blpapi_ServiceRegistrationOptions_setServicePriority(parameters, priority): ...
def blpapi_ServiceRegistrationOptions_setPartsToRegister(parameters, parts): ...
def blpapi_ServiceRegistrationOptions_getGroupId(parameters): ...
def blpapi_ServiceRegistrationOptions_getServicePriority(parameters): ...
def blpapi_ServiceRegistrationOptions_getPartsToRegister(parameters): ...
def blpapi_ZfpUtil_getOptionsForLeasedLines(sessionOptions, tlsOptions, remote): ...
