import datetime as dt
from typing import List, Optional

from ..internals import CorrelationId
from ..service import Service

class MessageProperties:
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    def destroy(self) -> None: ...
    def setCorrelationIds(self, cids: List[CorrelationId]) -> None: ...
    def setRecapType(
        self, recapType: int, fragmentType: Optional[int] = ...
    ) -> None: ...
    def setTimeReceived(self, timestamp: dt.datetime) -> None: ...
    def setRequestId(self, requestId: str) -> None: ...
    def setService(self, service: Service) -> None: ...
