import datetime as dt
from typing import Dict, Union, Optional

from ..name import Name

class MessageFormatter:
    def __init__(self, handle) -> None: ...
    def setElement(
        self,
        name: Union[Name, str],
        value: Optional[Union[bool, str, int, float, dt.time, dt.datetime, Name]],
    ) -> None: ...
    def pushElement(self, name: Union[Name, str]) -> None: ...
    def popElement(self) -> None: ...
    def appendValue(
        self, value: Union[bool, str, int, float, dt.time, dt.datetime, Name]
    ) -> None: ...
    def appendElement(self) -> None: ...
    def formatMessageJson(self, jsonMessage: str) -> None: ...
    def formatMessageXml(self, xmlMessage: str) -> None: ...
    def formatMessageDict(self, dictMessage: Dict) -> None: ...
